//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.07 at 12:45:54 PM EST 
//

package iso.std.iso._20022.tech.xsd.pacs_008_001;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for GroupHeader70 complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="GroupHeader70">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MsgId" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.06}Max35Text"/>
 *         &lt;element name="CreDtTm" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.06}ISODateTime"/>
 *         &lt;element name="BtchBookg" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.06}BatchBookingIndicator" minOccurs="0"/>
 *         &lt;element name="NbOfTxs" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.06}Max15NumericText"/>
 *         &lt;element name="CtrlSum" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.06}DecimalNumber" minOccurs="0"/>
 *         &lt;element name="TtlIntrBkSttlmAmt" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.06}ActiveCurrencyAndAmount" minOccurs="0"/>
 *         &lt;element name="IntrBkSttlmDt" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.06}ISODate" minOccurs="0"/>
 *         &lt;element name="SttlmInf" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.06}SettlementInstruction4"/>
 *         &lt;element name="PmtTpInf" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.06}PaymentTypeInformation21" minOccurs="0"/>
 *         &lt;element name="InstgAgt" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.06}BranchAndFinancialInstitutionIdentification5" minOccurs="0"/>
 *         &lt;element name="InstdAgt" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.06}BranchAndFinancialInstitutionIdentification5" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GroupHeader70", propOrder = { "msgId", "creDtTm", "btchBookg", "nbOfTxs", "ctrlSum",
		"ttlIntrBkSttlmAmt", "intrBkSttlmDt", "sttlmInf", "pmtTpInf", "instgAgt", "instdAgt" })
public class GroupHeader70 {

	@XmlElement(name = "MsgId", required = true)
	protected String msgId;
	@XmlElement(name = "CreDtTm", required = true)
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar creDtTm;
	@XmlElement(name = "BtchBookg")
	protected Boolean btchBookg;
	@XmlElement(name = "NbOfTxs", required = true)
	protected String nbOfTxs;
	@XmlElement(name = "CtrlSum")
	protected BigDecimal ctrlSum;
	@XmlElement(name = "TtlIntrBkSttlmAmt")
	protected ActiveCurrencyAndAmount ttlIntrBkSttlmAmt = new ActiveCurrencyAndAmount();
	@XmlElement(name = "IntrBkSttlmDt")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar intrBkSttlmDt;
	@XmlElement(name = "SttlmInf", required = true)
	protected SettlementInstruction4 sttlmInf = new SettlementInstruction4();
	@XmlElement(name = "PmtTpInf")
	protected PaymentTypeInformation21 pmtTpInf = new PaymentTypeInformation21();
	@XmlElement(name = "InstgAgt")
	protected BranchAndFinancialInstitutionIdentification5 instgAgt = new BranchAndFinancialInstitutionIdentification5();
	@XmlElement(name = "InstdAgt")
	protected BranchAndFinancialInstitutionIdentification5 instdAgt = new BranchAndFinancialInstitutionIdentification5();

	/**
	 * Gets the value of the msgId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMsgId() {
		return msgId;
	}

	/**
	 * Sets the value of the msgId property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setMsgId(String value) {
		this.msgId = value;
	}

	/**
	 * Gets the value of the creDtTm property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getCreDtTm() {
		return creDtTm;
	}

	/**
	 * Sets the value of the creDtTm property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setCreDtTm(XMLGregorianCalendar value) {
		this.creDtTm = value;
	}

	/**
	 * Gets the value of the btchBookg property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isBtchBookg() {
		return btchBookg;
	}

	/**
	 * Sets the value of the btchBookg property.
	 * 
	 * @param value allowed object is {@link Boolean }
	 * 
	 */
	public void setBtchBookg(Boolean value) {
		this.btchBookg = value;
	}

	/**
	 * Gets the value of the nbOfTxs property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNbOfTxs() {
		return nbOfTxs;
	}

	/**
	 * Sets the value of the nbOfTxs property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setNbOfTxs(String value) {
		this.nbOfTxs = value;
	}

	/**
	 * Gets the value of the ctrlSum property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getCtrlSum() {
		return ctrlSum;
	}

	/**
	 * Sets the value of the ctrlSum property.
	 * 
	 * @param value allowed object is {@link BigDecimal }
	 * 
	 */
	public void setCtrlSum(BigDecimal value) {
		this.ctrlSum = value;
	}

	/**
	 * Gets the value of the ttlIntrBkSttlmAmt property.
	 * 
	 * @return possible object is {@link ActiveCurrencyAndAmount }
	 * 
	 */
	public ActiveCurrencyAndAmount getTtlIntrBkSttlmAmt() {
		if (ttlIntrBkSttlmAmt == null) {
			return new ActiveCurrencyAndAmount();
		} else {
			return ttlIntrBkSttlmAmt;
		}
	}

	/**
	 * Sets the value of the ttlIntrBkSttlmAmt property.
	 * 
	 * @param value allowed object is {@link ActiveCurrencyAndAmount }
	 * 
	 */
	public void setTtlIntrBkSttlmAmt(ActiveCurrencyAndAmount value) {
		this.ttlIntrBkSttlmAmt = value;
	}

	/**
	 * Gets the value of the intrBkSttlmDt property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getIntrBkSttlmDt() {
		return intrBkSttlmDt;
	}

	/**
	 * Sets the value of the intrBkSttlmDt property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setIntrBkSttlmDt(XMLGregorianCalendar value) {
		this.intrBkSttlmDt = value;
	}

	/**
	 * Gets the value of the sttlmInf property.
	 * 
	 * @return possible object is {@link SettlementInstruction4 }
	 * 
	 */
	public SettlementInstruction4 getSttlmInf() {
		if (sttlmInf == null) {
			return new SettlementInstruction4();
		} else {
			return sttlmInf;
		}
	}

	/**
	 * Sets the value of the sttlmInf property.
	 * 
	 * @param value allowed object is {@link SettlementInstruction4 }
	 * 
	 */
	public void setSttlmInf(SettlementInstruction4 value) {
		this.sttlmInf = value;
	}

	/**
	 * Gets the value of the pmtTpInf property.
	 * 
	 * @return possible object is {@link PaymentTypeInformation21 }
	 * 
	 */
	public PaymentTypeInformation21 getPmtTpInf() {
		return pmtTpInf;
	}

	/**
	 * Sets the value of the pmtTpInf property.
	 * 
	 * @param value allowed object is {@link PaymentTypeInformation21 }
	 * 
	 */
	public void setPmtTpInf(PaymentTypeInformation21 value) {
		this.pmtTpInf = value;
	}

	/**
	 * Gets the value of the instgAgt property.
	 * 
	 * @return possible object is
	 *         {@link BranchAndFinancialInstitutionIdentification5 }
	 * 
	 */
	public BranchAndFinancialInstitutionIdentification5 getInstgAgt() {
		if (instgAgt == null) {
			return new BranchAndFinancialInstitutionIdentification5();
		} else {
			return instgAgt;
		}
	}

	/**
	 * Sets the value of the instgAgt property.
	 * 
	 * @param value allowed object is
	 *              {@link BranchAndFinancialInstitutionIdentification5 }
	 * 
	 */
	public void setInstgAgt(BranchAndFinancialInstitutionIdentification5 value) {
		this.instgAgt = value;
	}

	/**
	 * Gets the value of the instdAgt property.
	 * 
	 * @return possible object is
	 *         {@link BranchAndFinancialInstitutionIdentification5 }
	 * 
	 */
	public BranchAndFinancialInstitutionIdentification5 getInstdAgt() {
		if (instdAgt == null) {
			return new BranchAndFinancialInstitutionIdentification5();
		} else {
			return instdAgt;
		}
	}

	/**
	 * Sets the value of the instdAgt property.
	 * 
	 * @param value allowed object is
	 *              {@link BranchAndFinancialInstitutionIdentification5 }
	 * 
	 */
	public void setInstdAgt(BranchAndFinancialInstitutionIdentification5 value) {
		this.instdAgt = value;
	}

	@Override
	public String toString() {
		return "GroupHeader70 [msgId=" + msgId + ", creDtTm=" + creDtTm + ", btchBookg=" + btchBookg + ", nbOfTxs="
				+ nbOfTxs + ", ctrlSum=" + ctrlSum + ", ttlIntrBkSttlmAmt=" + ttlIntrBkSttlmAmt + ", intrBkSttlmDt="
				+ intrBkSttlmDt + ", sttlmInf=" + sttlmInf + ", pmtTpInf=" + pmtTpInf + ", instgAgt=" + instgAgt
				+ ", instdAgt=" + instdAgt + "]";
	}

}
