//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.07 at 12:45:54 PM EST 
//


package tch;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import iso.std.iso._20022.tech.xsd.head_001_001.BusinessApplicationHeaderV01;


/**
 * <p>Java class for HdrAndData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HdrAndData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AppHdr" type="{urn:iso:std:iso:20022:tech:xsd:head.001.001.01}BusinessApplicationHeaderV01"/>
 *         &lt;choice>
 *           &lt;element name="Acknowledgement" type="{urn:iso:std:iso:20022:tech:xsd:camt.035.001.03}Document"/>
 *           &lt;element name="ResponseRequestForInformation" type="{urn:iso:std:iso:20022:tech:xsd:camt.028.001.06}Document"/>
 *           &lt;element name="RequestForInformation" type="{urn:iso:std:iso:20022:tech:xsd:camt.026.001.05}Document"/>
 *           &lt;element name="CreditTransfer" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.06}Document"/>
 *           &lt;element name="ResponseCreditTransfer" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}Document"/>
 *           &lt;element name="ReturnOfFunds" type="{urn:iso:std:iso:20022:tech:xsd:camt.056.001.05}Document"/>
 *           &lt;element name="PaymentRequest" type="{urn:iso:std:iso:20022:tech:xsd:pain.013.001.05}Document"/>
 *           &lt;element name="ResponsePaymentRequest" type="{urn:iso:std:iso:20022:tech:xsd:pain.014.001.05}Document"/>
 *           &lt;element name="ResponseReturnOfFunds" type="{urn:iso:std:iso:20022:tech:xsd:camt.029.001.06}Document"/>
 *           &lt;element name="StandaloneRemittance" type="{urn:iso:std:iso:20022:tech:xsd:remt.001.001.02}Document"/>
 *           &lt;element name="SystemNotificationEvent" type="{urn:iso:std:iso:20022:tech:xsd:admi.004.001.02}Document"/>
 *           &lt;element name="MessageReject" type="{urn:iso:std:iso:20022:tech:xsd:admi.002.001.01}Document"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HdrAndData", propOrder = {
    "appHdr",
    "acknowledgement",
    "responseRequestForInformation",
    "requestForInformation",
    "creditTransfer",
    "responseCreditTransfer",
    "returnOfFunds",
    "paymentRequest",
    "responsePaymentRequest",
    "responseReturnOfFunds",
    "standaloneRemittance",
    "systemNotificationEvent",
    "messageReject"
})
public class HdrAndData {

    @XmlElement(name = "AppHdr", required = true)
    protected BusinessApplicationHeaderV01 appHdr;
    @XmlElement(name = "Acknowledgement")
    protected iso.std.iso._20022.tech.xsd.camt_035_001.Document acknowledgement;
    @XmlElement(name = "ResponseRequestForInformation")
    protected iso.std.iso._20022.tech.xsd.camt_028_001.Document responseRequestForInformation;
    @XmlElement(name = "RequestForInformation")
    protected iso.std.iso._20022.tech.xsd.camt_026_001.Document requestForInformation;
    @XmlElement(name = "CreditTransfer")
    protected iso.std.iso._20022.tech.xsd.pacs_008_001.Document creditTransfer;
    @XmlElement(name = "ResponseCreditTransfer")
    protected iso.std.iso._20022.tech.xsd.pacs_002_001.Document responseCreditTransfer;
    @XmlElement(name = "ReturnOfFunds")
    protected iso.std.iso._20022.tech.xsd.camt_056_001.Document returnOfFunds;
    @XmlElement(name = "PaymentRequest")
    protected iso.std.iso._20022.tech.xsd.pain_013_001.Document paymentRequest;
    @XmlElement(name = "ResponsePaymentRequest")
    protected iso.std.iso._20022.tech.xsd.pain_014_001.Document responsePaymentRequest;
    @XmlElement(name = "ResponseReturnOfFunds")
    protected iso.std.iso._20022.tech.xsd.camt_029_001.Document responseReturnOfFunds;
    @XmlElement(name = "StandaloneRemittance")
    protected iso.std.iso._20022.tech.xsd.remt_001_001.Document standaloneRemittance;
    @XmlElement(name = "SystemNotificationEvent")
    protected iso.std.iso._20022.tech.xsd.admi_004_001.Document systemNotificationEvent;
    @XmlElement(name = "MessageReject")
    protected iso.std.iso._20022.tech.xsd.admi_002_001.Document messageReject;

    /**
     * Gets the value of the appHdr property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessApplicationHeaderV01 }
     *     
     */
    public BusinessApplicationHeaderV01 getAppHdr() {
        return appHdr;
    }

    /**
     * Sets the value of the appHdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessApplicationHeaderV01 }
     *     
     */
    public void setAppHdr(BusinessApplicationHeaderV01 value) {
        this.appHdr = value;
    }

    /**
     * Gets the value of the acknowledgement property.
     * 
     * @return
     *     possible object is
     *     {@link iso.std.iso._20022.tech.xsd.camt_035_001.Document }
     *     
     */
    public iso.std.iso._20022.tech.xsd.camt_035_001.Document getAcknowledgement() {
        return acknowledgement;
    }

    /**
     * Sets the value of the acknowledgement property.
     * 
     * @param value
     *     allowed object is
     *     {@link iso.std.iso._20022.tech.xsd.camt_035_001.Document }
     *     
     */
    public void setAcknowledgement(iso.std.iso._20022.tech.xsd.camt_035_001.Document value) {
        this.acknowledgement = value;
    }

    /**
     * Gets the value of the responseRequestForInformation property.
     * 
     * @return
     *     possible object is
     *     {@link iso.std.iso._20022.tech.xsd.camt_028_001.Document }
     *     
     */
    public iso.std.iso._20022.tech.xsd.camt_028_001.Document getResponseRequestForInformation() {
        return responseRequestForInformation;
    }

    /**
     * Sets the value of the responseRequestForInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link iso.std.iso._20022.tech.xsd.camt_028_001.Document }
     *     
     */
    public void setResponseRequestForInformation(iso.std.iso._20022.tech.xsd.camt_028_001.Document value) {
        this.responseRequestForInformation = value;
    }

    /**
     * Gets the value of the requestForInformation property.
     * 
     * @return
     *     possible object is
     *     {@link iso.std.iso._20022.tech.xsd.camt_026_001.Document }
     *     
     */
    public iso.std.iso._20022.tech.xsd.camt_026_001.Document getRequestForInformation() {
        return requestForInformation;
    }

    /**
     * Sets the value of the requestForInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link iso.std.iso._20022.tech.xsd.camt_026_001.Document }
     *     
     */
    public void setRequestForInformation(iso.std.iso._20022.tech.xsd.camt_026_001.Document value) {
        this.requestForInformation = value;
    }

    /**
     * Gets the value of the creditTransfer property.
     * 
     * @return
     *     possible object is
     *     {@link iso.std.iso._20022.tech.xsd.pacs_008_001.Document }
     *     
     */
    public iso.std.iso._20022.tech.xsd.pacs_008_001.Document getCreditTransfer() {
        return creditTransfer;
    }

    /**
     * Sets the value of the creditTransfer property.
     * 
     * @param value
     *     allowed object is
     *     {@link iso.std.iso._20022.tech.xsd.pacs_008_001.Document }
     *     
     */
    public void setCreditTransfer(iso.std.iso._20022.tech.xsd.pacs_008_001.Document value) {
        this.creditTransfer = value;
    }

    /**
     * Gets the value of the responseCreditTransfer property.
     * 
     * @return
     *     possible object is
     *     {@link iso.std.iso._20022.tech.xsd.pacs_002_001.Document }
     *     
     */
    public iso.std.iso._20022.tech.xsd.pacs_002_001.Document getResponseCreditTransfer() {
        return responseCreditTransfer;
    }

    /**
     * Sets the value of the responseCreditTransfer property.
     * 
     * @param value
     *     allowed object is
     *     {@link iso.std.iso._20022.tech.xsd.pacs_002_001.Document }
     *     
     */
    public void setResponseCreditTransfer(iso.std.iso._20022.tech.xsd.pacs_002_001.Document value) {
        this.responseCreditTransfer = value;
    }

    /**
     * Gets the value of the returnOfFunds property.
     * 
     * @return
     *     possible object is
     *     {@link iso.std.iso._20022.tech.xsd.camt_056_001.Document }
     *     
     */
    public iso.std.iso._20022.tech.xsd.camt_056_001.Document getReturnOfFunds() {
        return returnOfFunds;
    }

    /**
     * Sets the value of the returnOfFunds property.
     * 
     * @param value
     *     allowed object is
     *     {@link iso.std.iso._20022.tech.xsd.camt_056_001.Document }
     *     
     */
    public void setReturnOfFunds(iso.std.iso._20022.tech.xsd.camt_056_001.Document value) {
        this.returnOfFunds = value;
    }

    /**
     * Gets the value of the paymentRequest property.
     * 
     * @return
     *     possible object is
     *     {@link iso.std.iso._20022.tech.xsd.pain_013_001.Document }
     *     
     */
    public iso.std.iso._20022.tech.xsd.pain_013_001.Document getPaymentRequest() {
        return paymentRequest;
    }

    /**
     * Sets the value of the paymentRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link iso.std.iso._20022.tech.xsd.pain_013_001.Document }
     *     
     */
    public void setPaymentRequest(iso.std.iso._20022.tech.xsd.pain_013_001.Document value) {
        this.paymentRequest = value;
    }

    /**
     * Gets the value of the responsePaymentRequest property.
     * 
     * @return
     *     possible object is
     *     {@link iso.std.iso._20022.tech.xsd.pain_014_001.Document }
     *     
     */
    public iso.std.iso._20022.tech.xsd.pain_014_001.Document getResponsePaymentRequest() {
        return responsePaymentRequest;
    }

    /**
     * Sets the value of the responsePaymentRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link iso.std.iso._20022.tech.xsd.pain_014_001.Document }
     *     
     */
    public void setResponsePaymentRequest(iso.std.iso._20022.tech.xsd.pain_014_001.Document value) {
        this.responsePaymentRequest = value;
    }

    /**
     * Gets the value of the responseReturnOfFunds property.
     * 
     * @return
     *     possible object is
     *     {@link iso.std.iso._20022.tech.xsd.camt_029_001.Document }
     *     
     */
    public iso.std.iso._20022.tech.xsd.camt_029_001.Document getResponseReturnOfFunds() {
        return responseReturnOfFunds;
    }

    /**
     * Sets the value of the responseReturnOfFunds property.
     * 
     * @param value
     *     allowed object is
     *     {@link iso.std.iso._20022.tech.xsd.camt_029_001.Document }
     *     
     */
    public void setResponseReturnOfFunds(iso.std.iso._20022.tech.xsd.camt_029_001.Document value) {
        this.responseReturnOfFunds = value;
    }

    /**
     * Gets the value of the standaloneRemittance property.
     * 
     * @return
     *     possible object is
     *     {@link iso.std.iso._20022.tech.xsd.remt_001_001.Document }
     *     
     */
    public iso.std.iso._20022.tech.xsd.remt_001_001.Document getStandaloneRemittance() {
        return standaloneRemittance;
    }

    /**
     * Sets the value of the standaloneRemittance property.
     * 
     * @param value
     *     allowed object is
     *     {@link iso.std.iso._20022.tech.xsd.remt_001_001.Document }
     *     
     */
    public void setStandaloneRemittance(iso.std.iso._20022.tech.xsd.remt_001_001.Document value) {
        this.standaloneRemittance = value;
    }

    /**
     * Gets the value of the systemNotificationEvent property.
     * 
     * @return
     *     possible object is
     *     {@link iso.std.iso._20022.tech.xsd.admi_004_001.Document }
     *     
     */
    public iso.std.iso._20022.tech.xsd.admi_004_001.Document getSystemNotificationEvent() {
        return systemNotificationEvent;
    }

    /**
     * Sets the value of the systemNotificationEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link iso.std.iso._20022.tech.xsd.admi_004_001.Document }
     *     
     */
    public void setSystemNotificationEvent(iso.std.iso._20022.tech.xsd.admi_004_001.Document value) {
        this.systemNotificationEvent = value;
    }

    /**
     * Gets the value of the messageReject property.
     * 
     * @return
     *     possible object is
     *     {@link iso.std.iso._20022.tech.xsd.admi_002_001.Document }
     *     
     */
    public iso.std.iso._20022.tech.xsd.admi_002_001.Document getMessageReject() {
        return messageReject;
    }

    /**
     * Sets the value of the messageReject property.
     * 
     * @param value
     *     allowed object is
     *     {@link iso.std.iso._20022.tech.xsd.admi_002_001.Document }
     *     
     */
    public void setMessageReject(iso.std.iso._20022.tech.xsd.admi_002_001.Document value) {
        this.messageReject = value;
    }

}
