//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.07 at 12:45:54 PM EST 
//

package iso.std.iso._20022.tech.xsd.pacs_002_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for AmendmentInformationDetails10 complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="AmendmentInformationDetails10">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrgnlMndtId" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}Max35Text" minOccurs="0"/>
 *         &lt;element name="OrgnlCdtrSchmeId" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}PartyIdentification43" minOccurs="0"/>
 *         &lt;element name="OrgnlCdtrAgt" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}BranchAndFinancialInstitutionIdentification5" minOccurs="0"/>
 *         &lt;element name="OrgnlCdtrAgtAcct" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}CashAccount24" minOccurs="0"/>
 *         &lt;element name="OrgnlDbtr" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}PartyIdentification43" minOccurs="0"/>
 *         &lt;element name="OrgnlDbtrAcct" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}CashAccount24" minOccurs="0"/>
 *         &lt;element name="OrgnlDbtrAgt" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}BranchAndFinancialInstitutionIdentification5" minOccurs="0"/>
 *         &lt;element name="OrgnlDbtrAgtAcct" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}CashAccount24" minOccurs="0"/>
 *         &lt;element name="OrgnlFnlColltnDt" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}ISODate" minOccurs="0"/>
 *         &lt;element name="OrgnlFrqcy" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}Frequency21Choice" minOccurs="0"/>
 *         &lt;element name="OrgnlRsn" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}MandateSetupReason1Choice" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AmendmentInformationDetails10", propOrder = { "orgnlMndtId", "orgnlCdtrSchmeId", "orgnlCdtrAgt",
		"orgnlCdtrAgtAcct", "orgnlDbtr", "orgnlDbtrAcct", "orgnlDbtrAgt", "orgnlDbtrAgtAcct", "orgnlFnlColltnDt",
		"orgnlFrqcy", "orgnlRsn" })
public class AmendmentInformationDetails10 {

	@XmlElement(name = "OrgnlMndtId")
	protected String orgnlMndtId;
	@XmlElement(name = "OrgnlCdtrSchmeId")
	protected PartyIdentification43 orgnlCdtrSchmeId = new PartyIdentification43();
	@XmlElement(name = "OrgnlCdtrAgt")
	protected BranchAndFinancialInstitutionIdentification5 orgnlCdtrAgt = new BranchAndFinancialInstitutionIdentification5();
	@XmlElement(name = "OrgnlCdtrAgtAcct")
	protected CashAccount24 orgnlCdtrAgtAcct = new CashAccount24();
	@XmlElement(name = "OrgnlDbtr")
	protected PartyIdentification43 orgnlDbtr = new PartyIdentification43();
	@XmlElement(name = "OrgnlDbtrAcct")
	protected CashAccount24 orgnlDbtrAcct = new CashAccount24();
	@XmlElement(name = "OrgnlDbtrAgt")
	protected BranchAndFinancialInstitutionIdentification5 orgnlDbtrAgt = new BranchAndFinancialInstitutionIdentification5();
	@XmlElement(name = "OrgnlDbtrAgtAcct")
	protected CashAccount24 orgnlDbtrAgtAcct = new CashAccount24();
	@XmlElement(name = "OrgnlFnlColltnDt")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar orgnlFnlColltnDt;
	@XmlElement(name = "OrgnlFrqcy")
	protected Frequency21Choice orgnlFrqcy = new Frequency21Choice();
	@XmlElement(name = "OrgnlRsn")
	protected MandateSetupReason1Choice orgnlRsn = new MandateSetupReason1Choice();

	/**
	 * Gets the value of the orgnlMndtId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOrgnlMndtId() {
		return orgnlMndtId;
	}

	/**
	 * Sets the value of the orgnlMndtId property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setOrgnlMndtId(String value) {
		this.orgnlMndtId = value;
	}

	/**
	 * Gets the value of the orgnlCdtrSchmeId property.
	 * 
	 * @return possible object is {@link PartyIdentification43 }
	 * 
	 */
	public PartyIdentification43 getOrgnlCdtrSchmeId() {
		return orgnlCdtrSchmeId;
	}

	/**
	 * Sets the value of the orgnlCdtrSchmeId property.
	 * 
	 * @param value allowed object is {@link PartyIdentification43 }
	 * 
	 */
	public void setOrgnlCdtrSchmeId(PartyIdentification43 value) {
		this.orgnlCdtrSchmeId = value;
	}

	/**
	 * Gets the value of the orgnlCdtrAgt property.
	 * 
	 * @return possible object is
	 *         {@link BranchAndFinancialInstitutionIdentification5 }
	 * 
	 */
	public BranchAndFinancialInstitutionIdentification5 getOrgnlCdtrAgt() {
		return orgnlCdtrAgt;
	}

	/**
	 * Sets the value of the orgnlCdtrAgt property.
	 * 
	 * @param value allowed object is
	 *              {@link BranchAndFinancialInstitutionIdentification5 }
	 * 
	 */
	public void setOrgnlCdtrAgt(BranchAndFinancialInstitutionIdentification5 value) {
		this.orgnlCdtrAgt = value;
	}

	/**
	 * Gets the value of the orgnlCdtrAgtAcct property.
	 * 
	 * @return possible object is {@link CashAccount24 }
	 * 
	 */
	public CashAccount24 getOrgnlCdtrAgtAcct() {
		return orgnlCdtrAgtAcct;
	}

	/**
	 * Sets the value of the orgnlCdtrAgtAcct property.
	 * 
	 * @param value allowed object is {@link CashAccount24 }
	 * 
	 */
	public void setOrgnlCdtrAgtAcct(CashAccount24 value) {
		this.orgnlCdtrAgtAcct = value;
	}

	/**
	 * Gets the value of the orgnlDbtr property.
	 * 
	 * @return possible object is {@link PartyIdentification43 }
	 * 
	 */
	public PartyIdentification43 getOrgnlDbtr() {
		return orgnlDbtr;
	}

	/**
	 * Sets the value of the orgnlDbtr property.
	 * 
	 * @param value allowed object is {@link PartyIdentification43 }
	 * 
	 */
	public void setOrgnlDbtr(PartyIdentification43 value) {
		this.orgnlDbtr = value;
	}

	/**
	 * Gets the value of the orgnlDbtrAcct property.
	 * 
	 * @return possible object is {@link CashAccount24 }
	 * 
	 */
	public CashAccount24 getOrgnlDbtrAcct() {
		return orgnlDbtrAcct;
	}

	/**
	 * Sets the value of the orgnlDbtrAcct property.
	 * 
	 * @param value allowed object is {@link CashAccount24 }
	 * 
	 */
	public void setOrgnlDbtrAcct(CashAccount24 value) {
		this.orgnlDbtrAcct = value;
	}

	/**
	 * Gets the value of the orgnlDbtrAgt property.
	 * 
	 * @return possible object is
	 *         {@link BranchAndFinancialInstitutionIdentification5 }
	 * 
	 */
	public BranchAndFinancialInstitutionIdentification5 getOrgnlDbtrAgt() {
		return orgnlDbtrAgt;
	}

	/**
	 * Sets the value of the orgnlDbtrAgt property.
	 * 
	 * @param value allowed object is
	 *              {@link BranchAndFinancialInstitutionIdentification5 }
	 * 
	 */
	public void setOrgnlDbtrAgt(BranchAndFinancialInstitutionIdentification5 value) {
		this.orgnlDbtrAgt = value;
	}

	/**
	 * Gets the value of the orgnlDbtrAgtAcct property.
	 * 
	 * @return possible object is {@link CashAccount24 }
	 * 
	 */
	public CashAccount24 getOrgnlDbtrAgtAcct() {
		return orgnlDbtrAgtAcct;
	}

	/**
	 * Sets the value of the orgnlDbtrAgtAcct property.
	 * 
	 * @param value allowed object is {@link CashAccount24 }
	 * 
	 */
	public void setOrgnlDbtrAgtAcct(CashAccount24 value) {
		this.orgnlDbtrAgtAcct = value;
	}

	/**
	 * Gets the value of the orgnlFnlColltnDt property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getOrgnlFnlColltnDt() {
		return orgnlFnlColltnDt;
	}

	/**
	 * Sets the value of the orgnlFnlColltnDt property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setOrgnlFnlColltnDt(XMLGregorianCalendar value) {
		this.orgnlFnlColltnDt = value;
	}

	/**
	 * Gets the value of the orgnlFrqcy property.
	 * 
	 * @return possible object is {@link Frequency21Choice }
	 * 
	 */
	public Frequency21Choice getOrgnlFrqcy() {
		return orgnlFrqcy;
	}

	/**
	 * Sets the value of the orgnlFrqcy property.
	 * 
	 * @param value allowed object is {@link Frequency21Choice }
	 * 
	 */
	public void setOrgnlFrqcy(Frequency21Choice value) {
		this.orgnlFrqcy = value;
	}

	/**
	 * Gets the value of the orgnlRsn property.
	 * 
	 * @return possible object is {@link MandateSetupReason1Choice }
	 * 
	 */
	public MandateSetupReason1Choice getOrgnlRsn() {
		return orgnlRsn;
	}

	/**
	 * Sets the value of the orgnlRsn property.
	 * 
	 * @param value allowed object is {@link MandateSetupReason1Choice }
	 * 
	 */
	public void setOrgnlRsn(MandateSetupReason1Choice value) {
		this.orgnlRsn = value;
	}

	@Override
	public String toString() {
		return "AmendmentInformationDetails10 [orgnlMndtId=" + orgnlMndtId + ", orgnlCdtrSchmeId=" + orgnlCdtrSchmeId
				+ ", orgnlCdtrAgt=" + orgnlCdtrAgt + ", orgnlCdtrAgtAcct=" + orgnlCdtrAgtAcct + ", orgnlDbtr="
				+ orgnlDbtr + ", orgnlDbtrAcct=" + orgnlDbtrAcct + ", orgnlDbtrAgt=" + orgnlDbtrAgt
				+ ", orgnlDbtrAgtAcct=" + orgnlDbtrAgtAcct + ", orgnlFnlColltnDt=" + orgnlFnlColltnDt + ", orgnlFrqcy="
				+ orgnlFrqcy + ", orgnlRsn=" + orgnlRsn + "]";
	}

}
