//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.07 at 12:45:54 PM EST 
//

package iso.std.iso._20022.tech.xsd.pacs_002_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for OriginalTransactionReference22 complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="OriginalTransactionReference22">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IntrBkSttlmAmt" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}ActiveOrHistoricCurrencyAndAmount" minOccurs="0"/>
 *         &lt;element name="Amt" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}AmountType4Choice" minOccurs="0"/>
 *         &lt;element name="IntrBkSttlmDt" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}ISODate" minOccurs="0"/>
 *         &lt;element name="ReqdColltnDt" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}ISODate" minOccurs="0"/>
 *         &lt;element name="ReqdExctnDt" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}ISODate" minOccurs="0"/>
 *         &lt;element name="CdtrSchmeId" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}PartyIdentification43" minOccurs="0"/>
 *         &lt;element name="SttlmInf" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}SettlementInstruction4" minOccurs="0"/>
 *         &lt;element name="PmtTpInf" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}PaymentTypeInformation25" minOccurs="0"/>
 *         &lt;element name="PmtMtd" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}PaymentMethod4Code" minOccurs="0"/>
 *         &lt;element name="MndtRltdInf" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}MandateRelatedInformation10" minOccurs="0"/>
 *         &lt;element name="RmtInf" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}RemittanceInformation11" minOccurs="0"/>
 *         &lt;element name="UltmtDbtr" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}PartyIdentification43" minOccurs="0"/>
 *         &lt;element name="Dbtr" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}PartyIdentification43" minOccurs="0"/>
 *         &lt;element name="DbtrAcct" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}CashAccount24" minOccurs="0"/>
 *         &lt;element name="DbtrAgt" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}BranchAndFinancialInstitutionIdentification5" minOccurs="0"/>
 *         &lt;element name="DbtrAgtAcct" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}CashAccount24" minOccurs="0"/>
 *         &lt;element name="CdtrAgt" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}BranchAndFinancialInstitutionIdentification5" minOccurs="0"/>
 *         &lt;element name="CdtrAgtAcct" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}CashAccount24" minOccurs="0"/>
 *         &lt;element name="Cdtr" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}PartyIdentification43" minOccurs="0"/>
 *         &lt;element name="CdtrAcct" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}CashAccount24" minOccurs="0"/>
 *         &lt;element name="UltmtCdtr" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}PartyIdentification43" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OriginalTransactionReference22", propOrder = { "intrBkSttlmAmt", "amt", "intrBkSttlmDt",
		"reqdColltnDt", "reqdExctnDt", "cdtrSchmeId", "sttlmInf", "pmtTpInf", "pmtMtd", "mndtRltdInf", "rmtInf",
		"ultmtDbtr", "dbtr", "dbtrAcct", "dbtrAgt", "dbtrAgtAcct", "cdtrAgt", "cdtrAgtAcct", "cdtr", "cdtrAcct",
		"ultmtCdtr" })
public class OriginalTransactionReference22 {

	@XmlElement(name = "IntrBkSttlmAmt")
	protected ActiveOrHistoricCurrencyAndAmount intrBkSttlmAmt = new ActiveOrHistoricCurrencyAndAmount();
	@XmlElement(name = "Amt")
	protected AmountType4Choice amt = new AmountType4Choice();
	@XmlElement(name = "IntrBkSttlmDt")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar intrBkSttlmDt;
	@XmlElement(name = "ReqdColltnDt")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar reqdColltnDt;
	@XmlElement(name = "ReqdExctnDt")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar reqdExctnDt;
	@XmlElement(name = "CdtrSchmeId")
	protected PartyIdentification43 cdtrSchmeId = new PartyIdentification43();
	@XmlElement(name = "SttlmInf")
	protected SettlementInstruction4 sttlmInf = new SettlementInstruction4();
	@XmlElement(name = "PmtTpInf")
	protected PaymentTypeInformation25 pmtTpInf = new PaymentTypeInformation25();
	@XmlElement(name = "PmtMtd")
	@XmlSchemaType(name = "string")
	protected PaymentMethod4Code pmtMtd;
	@XmlElement(name = "MndtRltdInf")
	protected MandateRelatedInformation10 mndtRltdInf = new MandateRelatedInformation10();
	@XmlElement(name = "RmtInf")
	protected RemittanceInformation11 rmtInf = new RemittanceInformation11();
	@XmlElement(name = "UltmtDbtr")
	protected PartyIdentification43 ultmtDbtr = new PartyIdentification43();
	@XmlElement(name = "Dbtr")
	protected PartyIdentification43 dbtr = new PartyIdentification43();
	@XmlElement(name = "DbtrAcct")
	protected CashAccount24 dbtrAcct = new CashAccount24();
	@XmlElement(name = "DbtrAgt")
	protected BranchAndFinancialInstitutionIdentification5 dbtrAgt = new BranchAndFinancialInstitutionIdentification5();
	@XmlElement(name = "DbtrAgtAcct")
	protected CashAccount24 dbtrAgtAcct = new CashAccount24();
	@XmlElement(name = "CdtrAgt")
	protected BranchAndFinancialInstitutionIdentification5 cdtrAgt = new BranchAndFinancialInstitutionIdentification5();
	@XmlElement(name = "CdtrAgtAcct")
	protected CashAccount24 cdtrAgtAcct = new CashAccount24();
	@XmlElement(name = "Cdtr")
	protected PartyIdentification43 cdtr = new PartyIdentification43();
	@XmlElement(name = "CdtrAcct")
	protected CashAccount24 cdtrAcct = new CashAccount24();
	@XmlElement(name = "UltmtCdtr")
	protected PartyIdentification43 ultmtCdtr = new PartyIdentification43();

	/**
	 * Gets the value of the intrBkSttlmAmt property.
	 * 
	 * @return possible object is {@link ActiveOrHistoricCurrencyAndAmount }
	 * 
	 */
	public ActiveOrHistoricCurrencyAndAmount getIntrBkSttlmAmt() {
		return intrBkSttlmAmt;
	}

	/**
	 * Sets the value of the intrBkSttlmAmt property.
	 * 
	 * @param value allowed object is {@link ActiveOrHistoricCurrencyAndAmount }
	 * 
	 */
	public void setIntrBkSttlmAmt(ActiveOrHistoricCurrencyAndAmount value) {
		this.intrBkSttlmAmt = value;
	}

	/**
	 * Gets the value of the amt property.
	 * 
	 * @return possible object is {@link AmountType4Choice }
	 * 
	 */
	public AmountType4Choice getAmt() {
		return amt;
	}

	/**
	 * Sets the value of the amt property.
	 * 
	 * @param value allowed object is {@link AmountType4Choice }
	 * 
	 */
	public void setAmt(AmountType4Choice value) {
		this.amt = value;
	}

	/**
	 * Gets the value of the intrBkSttlmDt property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getIntrBkSttlmDt() {
		return intrBkSttlmDt;
	}

	/**
	 * Sets the value of the intrBkSttlmDt property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setIntrBkSttlmDt(XMLGregorianCalendar value) {
		this.intrBkSttlmDt = value;
	}

	/**
	 * Gets the value of the reqdColltnDt property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getReqdColltnDt() {
		return reqdColltnDt;
	}

	/**
	 * Sets the value of the reqdColltnDt property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setReqdColltnDt(XMLGregorianCalendar value) {
		this.reqdColltnDt = value;
	}

	/**
	 * Gets the value of the reqdExctnDt property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getReqdExctnDt() {
		return reqdExctnDt;
	}

	/**
	 * Sets the value of the reqdExctnDt property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setReqdExctnDt(XMLGregorianCalendar value) {
		this.reqdExctnDt = value;
	}

	/**
	 * Gets the value of the cdtrSchmeId property.
	 * 
	 * @return possible object is {@link PartyIdentification43 }
	 * 
	 */
	public PartyIdentification43 getCdtrSchmeId() {
		return cdtrSchmeId;
	}

	/**
	 * Sets the value of the cdtrSchmeId property.
	 * 
	 * @param value allowed object is {@link PartyIdentification43 }
	 * 
	 */
	public void setCdtrSchmeId(PartyIdentification43 value) {
		this.cdtrSchmeId = value;
	}

	/**
	 * Gets the value of the sttlmInf property.
	 * 
	 * @return possible object is {@link SettlementInstruction4 }
	 * 
	 */
	public SettlementInstruction4 getSttlmInf() {
		return sttlmInf;
	}

	/**
	 * Sets the value of the sttlmInf property.
	 * 
	 * @param value allowed object is {@link SettlementInstruction4 }
	 * 
	 */
	public void setSttlmInf(SettlementInstruction4 value) {
		this.sttlmInf = value;
	}

	/**
	 * Gets the value of the pmtTpInf property.
	 * 
	 * @return possible object is {@link PaymentTypeInformation25 }
	 * 
	 */
	public PaymentTypeInformation25 getPmtTpInf() {
		return pmtTpInf;
	}

	/**
	 * Sets the value of the pmtTpInf property.
	 * 
	 * @param value allowed object is {@link PaymentTypeInformation25 }
	 * 
	 */
	public void setPmtTpInf(PaymentTypeInformation25 value) {
		this.pmtTpInf = value;
	}

	/**
	 * Gets the value of the pmtMtd property.
	 * 
	 * @return possible object is {@link PaymentMethod4Code }
	 * 
	 */
	public PaymentMethod4Code getPmtMtd() {
		return pmtMtd;
	}

	/**
	 * Sets the value of the pmtMtd property.
	 * 
	 * @param value allowed object is {@link PaymentMethod4Code }
	 * 
	 */
	public void setPmtMtd(PaymentMethod4Code value) {
		this.pmtMtd = value;
	}

	/**
	 * Gets the value of the mndtRltdInf property.
	 * 
	 * @return possible object is {@link MandateRelatedInformation10 }
	 * 
	 */
	public MandateRelatedInformation10 getMndtRltdInf() {
		return mndtRltdInf;
	}

	/**
	 * Sets the value of the mndtRltdInf property.
	 * 
	 * @param value allowed object is {@link MandateRelatedInformation10 }
	 * 
	 */
	public void setMndtRltdInf(MandateRelatedInformation10 value) {
		this.mndtRltdInf = value;
	}

	/**
	 * Gets the value of the rmtInf property.
	 * 
	 * @return possible object is {@link RemittanceInformation11 }
	 * 
	 */
	public RemittanceInformation11 getRmtInf() {
		return rmtInf;
	}

	/**
	 * Sets the value of the rmtInf property.
	 * 
	 * @param value allowed object is {@link RemittanceInformation11 }
	 * 
	 */
	public void setRmtInf(RemittanceInformation11 value) {
		this.rmtInf = value;
	}

	/**
	 * Gets the value of the ultmtDbtr property.
	 * 
	 * @return possible object is {@link PartyIdentification43 }
	 * 
	 */
	public PartyIdentification43 getUltmtDbtr() {
		return ultmtDbtr;
	}

	/**
	 * Sets the value of the ultmtDbtr property.
	 * 
	 * @param value allowed object is {@link PartyIdentification43 }
	 * 
	 */
	public void setUltmtDbtr(PartyIdentification43 value) {
		this.ultmtDbtr = value;
	}

	/**
	 * Gets the value of the dbtr property.
	 * 
	 * @return possible object is {@link PartyIdentification43 }
	 * 
	 */
	public PartyIdentification43 getDbtr() {
		return dbtr;
	}

	/**
	 * Sets the value of the dbtr property.
	 * 
	 * @param value allowed object is {@link PartyIdentification43 }
	 * 
	 */
	public void setDbtr(PartyIdentification43 value) {
		this.dbtr = value;
	}

	/**
	 * Gets the value of the dbtrAcct property.
	 * 
	 * @return possible object is {@link CashAccount24 }
	 * 
	 */
	public CashAccount24 getDbtrAcct() {
		return dbtrAcct;
	}

	/**
	 * Sets the value of the dbtrAcct property.
	 * 
	 * @param value allowed object is {@link CashAccount24 }
	 * 
	 */
	public void setDbtrAcct(CashAccount24 value) {
		this.dbtrAcct = value;
	}

	/**
	 * Gets the value of the dbtrAgt property.
	 * 
	 * @return possible object is
	 *         {@link BranchAndFinancialInstitutionIdentification5 }
	 * 
	 */
	public BranchAndFinancialInstitutionIdentification5 getDbtrAgt() {
		return dbtrAgt;
	}

	/**
	 * Sets the value of the dbtrAgt property.
	 * 
	 * @param value allowed object is
	 *              {@link BranchAndFinancialInstitutionIdentification5 }
	 * 
	 */
	public void setDbtrAgt(BranchAndFinancialInstitutionIdentification5 value) {
		this.dbtrAgt = value;
	}

	/**
	 * Gets the value of the dbtrAgtAcct property.
	 * 
	 * @return possible object is {@link CashAccount24 }
	 * 
	 */
	public CashAccount24 getDbtrAgtAcct() {
		return dbtrAgtAcct;
	}

	/**
	 * Sets the value of the dbtrAgtAcct property.
	 * 
	 * @param value allowed object is {@link CashAccount24 }
	 * 
	 */
	public void setDbtrAgtAcct(CashAccount24 value) {
		this.dbtrAgtAcct = value;
	}

	/**
	 * Gets the value of the cdtrAgt property.
	 * 
	 * @return possible object is
	 *         {@link BranchAndFinancialInstitutionIdentification5 }
	 * 
	 */
	public BranchAndFinancialInstitutionIdentification5 getCdtrAgt() {
		return cdtrAgt;
	}

	/**
	 * Sets the value of the cdtrAgt property.
	 * 
	 * @param value allowed object is
	 *              {@link BranchAndFinancialInstitutionIdentification5 }
	 * 
	 */
	public void setCdtrAgt(BranchAndFinancialInstitutionIdentification5 value) {
		this.cdtrAgt = value;
	}

	/**
	 * Gets the value of the cdtrAgtAcct property.
	 * 
	 * @return possible object is {@link CashAccount24 }
	 * 
	 */
	public CashAccount24 getCdtrAgtAcct() {
		return cdtrAgtAcct;
	}

	/**
	 * Sets the value of the cdtrAgtAcct property.
	 * 
	 * @param value allowed object is {@link CashAccount24 }
	 * 
	 */
	public void setCdtrAgtAcct(CashAccount24 value) {
		this.cdtrAgtAcct = value;
	}

	/**
	 * Gets the value of the cdtr property.
	 * 
	 * @return possible object is {@link PartyIdentification43 }
	 * 
	 */
	public PartyIdentification43 getCdtr() {
		return cdtr;
	}

	/**
	 * Sets the value of the cdtr property.
	 * 
	 * @param value allowed object is {@link PartyIdentification43 }
	 * 
	 */
	public void setCdtr(PartyIdentification43 value) {
		this.cdtr = value;
	}

	/**
	 * Gets the value of the cdtrAcct property.
	 * 
	 * @return possible object is {@link CashAccount24 }
	 * 
	 */
	public CashAccount24 getCdtrAcct() {
		return cdtrAcct;
	}

	/**
	 * Sets the value of the cdtrAcct property.
	 * 
	 * @param value allowed object is {@link CashAccount24 }
	 * 
	 */
	public void setCdtrAcct(CashAccount24 value) {
		this.cdtrAcct = value;
	}

	/**
	 * Gets the value of the ultmtCdtr property.
	 * 
	 * @return possible object is {@link PartyIdentification43 }
	 * 
	 */
	public PartyIdentification43 getUltmtCdtr() {
		return ultmtCdtr;
	}

	/**
	 * Sets the value of the ultmtCdtr property.
	 * 
	 * @param value allowed object is {@link PartyIdentification43 }
	 * 
	 */
	public void setUltmtCdtr(PartyIdentification43 value) {
		this.ultmtCdtr = value;
	}

}
