//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.07 at 12:45:54 PM EST 
//


package iso.std.iso._20022.tech.xsd.camt_056_001;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CancellationReason5Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CancellationReason5Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DUPL"/>
 *     &lt;enumeration value="AGNT"/>
 *     &lt;enumeration value="CURR"/>
 *     &lt;enumeration value="CUST"/>
 *     &lt;enumeration value="UPAY"/>
 *     &lt;enumeration value="CUTA"/>
 *     &lt;enumeration value="TECH"/>
 *     &lt;enumeration value="FRAD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CancellationReason5Code")
@XmlEnum
public enum CancellationReason5Code {

    DUPL,
    AGNT,
    CURR,
    CUST,
    UPAY,
    CUTA,
    TECH,
    FRAD;

    public String value() {
        return name();
    }

    public static CancellationReason5Code fromValue(String v) {
        return valueOf(v);
    }

}
