//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.07 at 12:45:54 PM EST 
//


package iso.std.iso._20022.tech.xsd.camt_029_001;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentCancellationRejection2Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PaymentCancellationRejection2Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="LEGL"/>
 *     &lt;enumeration value="AGNT"/>
 *     &lt;enumeration value="CUST"/>
 *     &lt;enumeration value="ARDT"/>
 *     &lt;enumeration value="NOAS"/>
 *     &lt;enumeration value="NOOR"/>
 *     &lt;enumeration value="AC04"/>
 *     &lt;enumeration value="AM04"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PaymentCancellationRejection2Code")
@XmlEnum
public enum PaymentCancellationRejection2Code {

    LEGL("LEGL"),
    AGNT("AGNT"),
    CUST("CUST"),
    ARDT("ARDT"),
    NOAS("NOAS"),
    NOOR("NOOR"),
    @XmlEnumValue("AC04")
    AC_04("AC04"),
    @XmlEnumValue("AM04")
    AM_04("AM04");
    private final String value;

    PaymentCancellationRejection2Code(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PaymentCancellationRejection2Code fromValue(String v) {
        for (PaymentCancellationRejection2Code c: PaymentCancellationRejection2Code.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
