//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.07 at 12:45:54 PM EST 
//


package iso.std.iso._20022.tech.xsd.admi_002_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Document complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Document">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="admi.002.001.01" type="{urn:iso:std:iso:20022:tech:xsd:admi.002.001.01}admi.002.001.01"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Document", propOrder = {
    "admi00200101"
})
public class Document {

    @XmlElement(name = "admi.002.001.01", required = true)
    protected Admi00200101 admi00200101;

    /**
     * Gets the value of the admi00200101 property.
     * 
     * @return
     *     possible object is
     *     {@link Admi00200101 }
     *     
     */
    public Admi00200101 getAdmi00200101() {
        return admi00200101;
    }

    /**
     * Sets the value of the admi00200101 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Admi00200101 }
     *     
     */
    public void setAdmi00200101(Admi00200101 value) {
        this.admi00200101 = value;
    }

}
