spec:
  template:
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: "0.2"
              memory: 256Mi
            limits:
              cpu: "1.0"
              memory: 256Mi
          env:
          - name: SPRING_APPLICATION_JSON
            value: '{"server":{"undertow":{"io-threads":1, "worker-threads":2 }}}'
          - name: BOOTSTRAP_SERVERS
            value: "rtp-demo-cluster-kafka-bootstrap:9092"
          - name: CREDIT_TRANS_DEBTOR_TOPIC
            value: mock-rtp-debtor-credit-transfer
          - name: CREDIT_TRANS_CREDITOR_TOPIC
            value: mock-rtp-creditor-credit-transfer
          - name: CREDITOR_ACK_TOPIC
            value: mock-rtp-creditor-acknowledgement
          - name: DEBTOR_CONFIRMATION_TOPIC
            value: mock-rtp-debtor-confirmation
          - name: CREDITOR_CONFIRMATION_TOPIC
            value: mock-rtp-creditor-confirmation
          - name: CONSUMER_MAX_POLL_RECORDS
            value: 500
          - name: CONSUMER_COUNT
            value: 1
          - name: CONSUMER_SEEK_TO
            value: end
          - name: CONSUMER_GROUP
            value: rtp-mock
          - name: ACKS
            value: 1
