spec:
  template:
    spec:
      containers:
        -
          resources:
            requests:
              cpu: "0.1"
              memory: 256Mi
            limits:
              cpu: "0.5"
              memory: 500Mi
          env:
            - name: BOOTSTRAP_SERVERS
              value: "rtp-demo-cluster-kafka-bootstrap:9092"
            - name: PRODUCER_TOPIC
              value: debtor-payments
            - name: SECURITY_PROTOCOL
              value: PLAINTEXT
            - name: SERIALIZER_CLASS
              value: rtp.demo.debtor.domain.model.payment.serde.PaymentSerializer
            - name: ACKS
              value: 1
            - name: DATABASE_URL
              value: "jdbc:mysql://mysql-56-rhel7:3306/rtpdb?autoReconnect=true"
            - name: DATABASE_USER
              value: dbuser
            - name: DATABASE_PASS
              value: dbpass
