//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.07 at 12:45:54 PM EST 
//


package iso.std.iso._20022.tech.xsd.camt_026_001;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UnableToApplyIncorrectInformation4Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="UnableToApplyIncorrectInformation4Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="IN01"/>
 *     &lt;enumeration value="IN02"/>
 *     &lt;enumeration value="IN03"/>
 *     &lt;enumeration value="IN04"/>
 *     &lt;enumeration value="IN05"/>
 *     &lt;enumeration value="IN06"/>
 *     &lt;enumeration value="IN07"/>
 *     &lt;enumeration value="IN08"/>
 *     &lt;enumeration value="IN09"/>
 *     &lt;enumeration value="IN10"/>
 *     &lt;enumeration value="IN11"/>
 *     &lt;enumeration value="IN12"/>
 *     &lt;enumeration value="IN13"/>
 *     &lt;enumeration value="IN14"/>
 *     &lt;enumeration value="IN15"/>
 *     &lt;enumeration value="IN16"/>
 *     &lt;enumeration value="IN17"/>
 *     &lt;enumeration value="IN18"/>
 *     &lt;enumeration value="IN19"/>
 *     &lt;enumeration value="MM20"/>
 *     &lt;enumeration value="MM21"/>
 *     &lt;enumeration value="MM22"/>
 *     &lt;enumeration value="MM25"/>
 *     &lt;enumeration value="MM26"/>
 *     &lt;enumeration value="MM27"/>
 *     &lt;enumeration value="MM28"/>
 *     &lt;enumeration value="MM29"/>
 *     &lt;enumeration value="MM30"/>
 *     &lt;enumeration value="MM31"/>
 *     &lt;enumeration value="MM32"/>
 *     &lt;enumeration value="IN33"/>
 *     &lt;enumeration value="MM34"/>
 *     &lt;enumeration value="MM35"/>
 *     &lt;enumeration value="IN36"/>
 *     &lt;enumeration value="IN37"/>
 *     &lt;enumeration value="IN38"/>
 *     &lt;enumeration value="IN39"/>
 *     &lt;enumeration value="NARR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "UnableToApplyIncorrectInformation4Code")
@XmlEnum
public enum UnableToApplyIncorrectInformation4Code {

    @XmlEnumValue("IN01")
    IN_01("IN01"),
    @XmlEnumValue("IN02")
    IN_02("IN02"),
    @XmlEnumValue("IN03")
    IN_03("IN03"),
    @XmlEnumValue("IN04")
    IN_04("IN04"),
    @XmlEnumValue("IN05")
    IN_05("IN05"),
    @XmlEnumValue("IN06")
    IN_06("IN06"),
    @XmlEnumValue("IN07")
    IN_07("IN07"),
    @XmlEnumValue("IN08")
    IN_08("IN08"),
    @XmlEnumValue("IN09")
    IN_09("IN09"),
    @XmlEnumValue("IN10")
    IN_10("IN10"),
    @XmlEnumValue("IN11")
    IN_11("IN11"),
    @XmlEnumValue("IN12")
    IN_12("IN12"),
    @XmlEnumValue("IN13")
    IN_13("IN13"),
    @XmlEnumValue("IN14")
    IN_14("IN14"),
    @XmlEnumValue("IN15")
    IN_15("IN15"),
    @XmlEnumValue("IN16")
    IN_16("IN16"),
    @XmlEnumValue("IN17")
    IN_17("IN17"),
    @XmlEnumValue("IN18")
    IN_18("IN18"),
    @XmlEnumValue("IN19")
    IN_19("IN19"),
    @XmlEnumValue("MM20")
    MM_20("MM20"),
    @XmlEnumValue("MM21")
    MM_21("MM21"),
    @XmlEnumValue("MM22")
    MM_22("MM22"),
    @XmlEnumValue("MM25")
    MM_25("MM25"),
    @XmlEnumValue("MM26")
    MM_26("MM26"),
    @XmlEnumValue("MM27")
    MM_27("MM27"),
    @XmlEnumValue("MM28")
    MM_28("MM28"),
    @XmlEnumValue("MM29")
    MM_29("MM29"),
    @XmlEnumValue("MM30")
    MM_30("MM30"),
    @XmlEnumValue("MM31")
    MM_31("MM31"),
    @XmlEnumValue("MM32")
    MM_32("MM32"),
    @XmlEnumValue("IN33")
    IN_33("IN33"),
    @XmlEnumValue("MM34")
    MM_34("MM34"),
    @XmlEnumValue("MM35")
    MM_35("MM35"),
    @XmlEnumValue("IN36")
    IN_36("IN36"),
    @XmlEnumValue("IN37")
    IN_37("IN37"),
    @XmlEnumValue("IN38")
    IN_38("IN38"),
    @XmlEnumValue("IN39")
    IN_39("IN39"),
    NARR("NARR");
    private final String value;

    UnableToApplyIncorrectInformation4Code(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static UnableToApplyIncorrectInformation4Code fromValue(String v) {
        for (UnableToApplyIncorrectInformation4Code c: UnableToApplyIncorrectInformation4Code.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
