apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: mock-rtp-debtor-confirmation
  labels:
    strimzi.io/cluster: rtp-demo-cluster
spec:
  partitions: 50
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
