apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: rtp-demo-cluster
spec:
  kafka:
    replicas: 3
    listeners:
      external:
        type: loadbalancer
        authentication:
          type: tls
      plain: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
