spec:
  template:
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: "0.2"
              memory: 500Mi
            limits:
              cpu: "1.0"
              memory: 500Mi
          env:
            - name: BOOTSTRAP_SERVERS
              value: "rtp-demo-cluster-kafka-bootstrap:9092"
