spec:
  template:
    spec:
      containers:
        -
#          resources:
#            requests:
#              cpu: "0.2"
#              memory: 256Mi
#            limits:
#              cpu: "1.0"
#              memory: 256Mi
          env:
            - name: BOOTSTRAP_SERVERS
              value: "rtp-demo-cluster-kafka-bootstrap:9092"
            - name: CREDITOR_COMPLETED_PAYMENTS_TOPIC
              value: creditor-completed-payments
            - name: CREDITOR_PAYMENTS_TOPIC
              value: creditor-payments
            - name: CREDITOR_CONFIRMATION_TOPIC
              value: creditor-payment-confirmation
            - name: APPLICATION_ID
              value: creditor-complete-payment
            - name: CLIENT_ID
              value: creditor-complete-payment-client
            - name: DATABASE_URL
              value: "jdbc:mysql://mysql-56-rhel7:3306/rtpdb?autoReconnect=true"
            - name: DATABASE_USER
              value: dbuser
            - name: DATABASE_PASS
              value: dbpass