create table CUSTOMER(

    ID        BIGINT  NOT NULL AUTO_INCREMENT,
    
    UNIQUE_ID          VARCHAR(256) NOT NULL,

    FIRST_NM          VARCHAR(256) NOT NULL,

    LAST_NM          VARCHAR(256) NOT NULL,

    ACCT_NO  VARCHAR(16) NOT NULL,

    FAV_CLR          VARCHAR(256),

    CREATED_BY VARCHAR(256) NOT NULL,

    CREATE_DT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    UPDATED_BY VARCHAR(256),

    UPDATE_DT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    PRIMARY KEY (ID)

);